
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ermaz0018
 */
public class FamilyBudget extends javax.swing.JFrame {

    /**
     * Creates new form FamilyBudget
     */
    public FamilyBudget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        header = new javax.swing.JSeparator();
        helpLabel = new javax.swing.JLabel();
        housingLabel = new javax.swing.JLabel();
        transportLabel = new javax.swing.JLabel();
        lifeLabel = new javax.swing.JLabel();
        savingLabel = new javax.swing.JLabel();
        incomeLabel = new javax.swing.JLabel();
        housingInput = new javax.swing.JTextField();
        transportInput = new javax.swing.JTextField();
        lifeInput = new javax.swing.JTextField();
        savingInput = new javax.swing.JTextField();
        incomeInput = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        graphPanel = new javax.swing.JPanel();
        title2Label = new javax.swing.JLabel();
        housingPercentLabel = new javax.swing.JLabel();
        transportPercentLabel = new javax.swing.JLabel();
        lifePercentLabel = new javax.swing.JLabel();
        savingsPercentLabel = new javax.swing.JLabel();
        housingPercent = new javax.swing.JLabel();
        transportPercent = new javax.swing.JLabel();
        lifePercent = new javax.swing.JLabel();
        savingsPercent = new javax.swing.JLabel();
        header2 = new javax.swing.JSeparator();
        housingBar = new javax.swing.JLabel();
        transportBar = new javax.swing.JLabel();
        lifeBar = new javax.swing.JLabel();
        savingBar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        housingOutput = new javax.swing.JLabel();
        transportOutput = new javax.swing.JLabel();
        lifeOutput = new javax.swing.JLabel();
        savingsOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputPanel.setBackground(new java.awt.Color(255, 255, 255));
        inputPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 204)));

        titleLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        titleLabel1.setText("Family Budget");

        header.setForeground(new java.awt.Color(0, 0, 0));

        helpLabel.setText("Enter the amount you spend on each category each month:");

        housingLabel.setText("Housing:");

        transportLabel.setText("Transportation:");

        lifeLabel.setText("Life:");

        savingLabel.setText("Savings:");

        incomeLabel.setText("Enter your monghtly net income:");

        housingInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housingInputActionPerformed(evt);
            }
        });

        lifeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lifeInputActionPerformed(evt);
            }
        });

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(titleLabel1))
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(incomeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(incomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(helpLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(housingLabel)
                            .addComponent(transportLabel)
                            .addComponent(lifeLabel)
                            .addComponent(savingLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(savingInput, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lifeInput)
                            .addComponent(transportInput)
                            .addComponent(housingInput))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(calculateButton)
                .addGap(41, 41, 41))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addComponent(titleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpLabel)
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housingLabel)
                    .addComponent(housingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transportLabel)
                    .addComponent(transportInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lifeLabel)
                    .addComponent(lifeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingLabel)
                    .addComponent(savingInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incomeLabel)
                    .addComponent(incomeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        graphPanel.setBackground(new java.awt.Color(153, 255, 153));
        graphPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 204)));

        title2Label.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        title2Label.setText("Monthly Spending");

        housingPercentLabel.setText("Housing:");

        transportPercentLabel.setText("Transportation:");

        lifePercentLabel.setText("Life:");

        savingsPercentLabel.setText("Savings:");

        housingPercent.setForeground(new java.awt.Color(51, 51, 255));
        housingPercent.setText("0");

        transportPercent.setForeground(new java.awt.Color(0, 0, 255));
        transportPercent.setText("0");

        lifePercent.setForeground(new java.awt.Color(0, 0, 255));
        lifePercent.setText("0");

        savingsPercent.setForeground(new java.awt.Color(0, 0, 255));
        savingsPercent.setText("0");

        header2.setForeground(new java.awt.Color(0, 0, 0));

        housingBar.setBackground(new java.awt.Color(255, 0, 0));
        housingBar.setForeground(new java.awt.Color(255, 0, 0));
        housingBar.setFocusable(false);
        housingBar.setOpaque(true);

        transportBar.setBackground(new java.awt.Color(0, 0, 255));
        transportBar.setForeground(new java.awt.Color(0, 0, 255));
        transportBar.setText(".");
        transportBar.setAlignmentY(0.0F);
        transportBar.setOpaque(true);

        lifeBar.setBackground(new java.awt.Color(255, 255, 0));
        lifeBar.setForeground(new java.awt.Color(255, 255, 0));
        lifeBar.setText(".");
        lifeBar.setToolTipText("");
        lifeBar.setOpaque(true);

        savingBar.setBackground(new java.awt.Color(255, 0, 255));
        savingBar.setForeground(new java.awt.Color(255, 0, 255));
        savingBar.setText(".");
        savingBar.setOpaque(true);

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header2)
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graphPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(title2Label))
                    .addGroup(graphPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, graphPanelLayout.createSequentialGroup()
                                .addComponent(transportPercentLabel)
                                .addGap(18, 18, 18)
                                .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(graphPanelLayout.createSequentialGroup()
                                        .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(transportPercent)
                                            .addComponent(lifePercent))
                                        .addGap(18, 18, 18)
                                        .addComponent(lifeBar, javax.swing.GroupLayout.DEFAULT_SIZE, 8, Short.MAX_VALUE))
                                    .addGroup(graphPanelLayout.createSequentialGroup()
                                        .addComponent(savingsPercent)
                                        .addGap(18, 18, 18)
                                        .addComponent(savingBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, graphPanelLayout.createSequentialGroup()
                                .addComponent(housingPercentLabel)
                                .addGap(52, 52, 52)
                                .addComponent(housingPercent)
                                .addGap(18, 18, 18)
                                .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(transportBar)
                                    .addComponent(housingBar)))))
                    .addGroup(graphPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lifePercentLabel))
                    .addGroup(graphPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(savingsPercentLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graphPanelLayout.createSequentialGroup()
                        .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(housingPercentLabel)
                            .addComponent(housingPercent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transportPercentLabel)
                            .addComponent(transportPercent)
                            .addComponent(transportBar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lifePercentLabel)
                            .addComponent(lifePercent)
                            .addComponent(lifeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savingsPercentLabel)
                            .addComponent(savingsPercent)
                            .addComponent(savingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(housingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        housingOutput.setForeground(new java.awt.Color(255, 255, 255));
        housingOutput.setText("Awaiting your input...");

        transportOutput.setForeground(new java.awt.Color(255, 255, 255));
        transportOutput.setText("Awaiting your input...");

        lifeOutput.setForeground(new java.awt.Color(255, 255, 255));
        lifeOutput.setText("Awaiting your input...");

        savingsOutput.setForeground(new java.awt.Color(255, 255, 255));
        savingsOutput.setText("Awaiting your input...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(housingOutput)
                    .addComponent(transportOutput)
                    .addComponent(lifeOutput)
                    .addComponent(savingsOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(housingOutput)
                .addGap(18, 18, 18)
                .addComponent(transportOutput)
                .addGap(18, 18, 18)
                .addComponent(lifeOutput)
                .addGap(18, 18, 18)
                .addComponent(savingsOutput)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void housingInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housingInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_housingInputActionPerformed

    private void lifeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lifeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lifeInputActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        double housing;      //Declares the variables
        double transport;
        double life;
        double saving;
        double income;
        String bar = "";

        housing = Double.parseDouble(housingInput.getText());        //Sets the variables
        transport = Double.parseDouble(transportInput.getText());
        life = Double.parseDouble(lifeInput.getText());
        saving = Double.parseDouble(savingInput.getText());
        income = Double.parseDouble(incomeInput.getText());

        housing = (housing / income) * 100;  //Turns all the numbers into percentages
        transport = (transport / income) * 100;
        life = (life / income) * 100;
        saving = (saving / income) * 100;

        housing = Math.round(housing);        //Rounds all the variables so they're not super long
        transport = Math.round(transport);
        life = Math.round(life);
        saving = Math.round(saving);

        housingPercent.setText(Double.toString((housing)) + "%");
        for (int i = 0; i <= housing; i++) {
            bar += "-";
        }
        housingBar.setText(bar);
        bar = "";
        transportPercent.setText(Double.toString(transport) + "%");
        for (int u = 0; u <= transport; u++) {
            bar += "-";
        }
        transportBar.setText(bar);
        bar = "";
        lifePercent.setText(Double.toString(life) + "%");
        for (int i = 0; i <= life; i++) {
            bar += "-";
        }
        lifeBar.setText(bar);
        bar = "";
        savingsPercent.setText(Double.toString(saving) + "%");
        for (int i = 0; i <= saving; i++) {
            bar += "-";
        }
        savingBar.setText(bar);

        if (housing > 25) {
            housingOutput.setText("You're spending too much on housing!");
        } else {
            housingOutput.setText("Yay! You're not spending too much on housing!");
        }
        if (transport > 25) {
            transportOutput.setText("You're spending too much on transport!");
        } else {
            transportOutput.setText("Yay! You're not spending too much on transport!");
        }
        if (life > 25) {
            lifeOutput.setText("You're spending too much on life!");
        } else {
            lifeOutput.setText("Yay! You're not spending too much on life!");
        }
        if (saving > 25) {
            savingsOutput.setText("You're spending too much on saving!");
        } else {
            savingsOutput.setText("Yay! You're not spending too much on saving!");
        }

    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilyBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilyBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilyBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilyBudget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilyBudget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JSeparator header;
    private javax.swing.JSeparator header2;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel housingBar;
    private javax.swing.JTextField housingInput;
    private javax.swing.JLabel housingLabel;
    private javax.swing.JLabel housingOutput;
    private javax.swing.JLabel housingPercent;
    private javax.swing.JLabel housingPercentLabel;
    private javax.swing.JTextField incomeInput;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lifeBar;
    private javax.swing.JTextField lifeInput;
    private javax.swing.JLabel lifeLabel;
    private javax.swing.JLabel lifeOutput;
    private javax.swing.JLabel lifePercent;
    private javax.swing.JLabel lifePercentLabel;
    private javax.swing.JLabel savingBar;
    private javax.swing.JTextField savingInput;
    private javax.swing.JLabel savingLabel;
    private javax.swing.JLabel savingsOutput;
    private javax.swing.JLabel savingsPercent;
    private javax.swing.JLabel savingsPercentLabel;
    private javax.swing.JLabel title2Label;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel transportBar;
    private javax.swing.JTextField transportInput;
    private javax.swing.JLabel transportLabel;
    private javax.swing.JLabel transportOutput;
    private javax.swing.JLabel transportPercent;
    private javax.swing.JLabel transportPercentLabel;
    // End of variables declaration//GEN-END:variables
}
